version: '2.1'
services:

  # The Application
  app:
    image: lemp-app
    container_name: lemp-app
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        - WITH_XDEBUG=${WITH_XDEBUG}
        - XDEBUG_TRIGGER_PROFILER=${XDEBUG_TRIGGER_PROFILER}
        - XDEBUG_PROFILER_DIR=${XDEBUG_PROFILER_DIR}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=database"
      - "PHP_IDE_CONFIG=${PHP_IDE_CONFIG}"
      - "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
      - "APP_ENV=${APP_ENV}"
      - "CONTAINER_ROLE=app"

  # The Web Server
  web:
    container_name: lemp-web
    build:
      context: ./
      args:
        - WITH_BASIC_AUTH=${WITH_BASIC_AUTH}
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - "${APP_PORT}:80"
    environment:
      - "CONTAINER_ROLE=web"

  # The Database
  database:
    container_name: lemp-db
    image: mariadb:10.5.13
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${TIMEZONE}"
    ports:
        - "${FORWARD_DB_PORT}:${DB_PORT}"

volumes:
  dbdata:
    driver: local
